name: pyrolyse.notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions>=0.5
  - matplotlib>=3.1
  - numpy>=1.18
  - pyrosetta>=2020.38
